AnimeStore.WebUI/Controllers/CartController.cs
using AnimeStore.Domain.Abstract;
using AnimeStore.Domain.Entities;
using AnimeStore.WebUI.Core.Abstract;
using AnimeStore.WebUI.Models;
using System.Linq;
using System.Text.RegularExpressions;
using System.Web.Mvc;

namespace AnimeStore.WebUI.Controllers
{
    public class CartController : Controller
    {
        private readonly IOrderRepository orderRepository;
        private readonly IOrderItemRepository orderItemRepository;
        private readonly IUserService userService;
        private readonly IBasketService basketService;

        public CartController(IOrderRepository orderRepository,
            IOrderItemRepository orderItemRepository, IUserService userService,
            IBasketService basketService)
        {
            this.orderRepository = orderRepository;
            this.orderItemRepository = orderItemRepository;
            this.userService = userService;
            this.basketService = basketService;
        }

        public ActionResult Step1()
        {
            Order order = basketService.GetCurrentOrder();

            if (order.OrderItems.Count == 0)
            {
                return RedirectToAction("Index", "Home");
            }

            decimal totalPrice = 0;
            foreach (var oi in order.OrderItems)
            {
                oi.PriceForComplect = oi.Product.Price;
                totalPrice += oi.PriceForComplect * oi.NumOfComplects;
                orderItemRepository.SaveOrderItem(oi);
            }
            order.TotalPrice = totalPrice;

            orderRepository.SaveOrder(order);
            CartIndexViewModel cartModel = new CartIndexViewModel();
            cartModel.Order = order;
            cartModel.OrderItems = order.OrderItems.ToList();

            return View(cartModel);
        }

        [HttpGet]
        [AllowAnonymous]
        public ActionResult Step2()
        {
            LoginOrRegistrationModel model = new LoginOrRegistrationModel();

            return View(model);
        }

        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public ActionResult Step2(LoginOrRegistrationModel model)
        {

            if (model.LoginModel != null)
            {
                if (ModelState.IsValid && userService.LoginUser(model.LoginModel.Login, 
                    model.LoginModel.Password, model.LoginModel.RememberMe))
                {
                    return RedirectToAction("Step3");
                }

                ModelState.AddModelError("modelError",
                            "Неверный логин или пароль");
            }
            else
            {
                if (!ModelState.IsValid)
                {
                    return View(model);
                } 

                if (userService.IsUserWithLoginExists(model.RegistrationModel.Login))
                {
                    ModelState.AddModelError("NotUniqueUserError",
                        "Пользователь с таким логином уже зарегистрирован!");
                }
                Regex regex = new Regex("^[a-zA-Z0-9]*$");
                if (!regex.IsMatch(model.RegistrationModel.Login))
                {
                    ModelState.AddModelError("RegistrationModel.Login",
                        "Логин должен состоять только с цифр и латинских букв");
                }
                if (userService.IsUserWithEmailExists(model.RegistrationModel.Email))
                {
                    ModelState.AddModelError("NotUniqueUserError",
                        "Пользователь с таким email уже зарегистрирован!");
                }
                regex = new Regex("[0-9]+");
                if (regex.IsMatch(model.RegistrationModel.FirstName))
                {
                    ModelState.AddModelError("RegistrationModel.FirstName",
                        "В имени не должно быть цифр");
                }
                if (regex.IsMatch(model.RegistrationModel.LastName))
                {
                    ModelState.AddModelError("RegistrationModel.LastName",
                        "В фамилии не должно быть цифр");
                }
                if (ModelState.IsValid)
                {
                    CreateUserModel createUserModel = userService.CreateUser(model.RegistrationModel);
                    if (createUserModel.IsSuccess)
                    {
                        userService.LoginUser(model.RegistrationModel.Login, model.RegistrationModel.Password);
                        return RedirectToAction("Step3");
                    }

                    ModelState.AddModelError("NotUniqueUserError", createUserModel.ErrorMessage);
                }
            }

            return View(model);
        }

        public ActionResult Step3()
        {
            if (!userService.IsAuthenticated())
            {
                return RedirectToAction("Step2");
            }

            Order order = basketService.GetCurrentOrder();

            if (order.OrderItems.Count == 0)
            {
                return RedirectToAction("Index", "Home");
            }

            CartIndexViewModel cartModel = new CartIndexViewModel();
            cartModel.Order = order;
            cartModel.OrderItems = order.OrderItems.ToList();
            cartModel.User = userService.GetCurrentUser();

            return View(cartModel);
        }

        public ActionResult Step4()
        {
            if (!userService.IsAuthenticated())
            {
                return RedirectToAction("Step2");
            }

            Order order = basketService.GetCurrentOrder();

            if (order.OrderItems.Count == 0)
            {
                return RedirectToAction("Index", "Home");
            }

            basketService.ConfirmOrder();

            return View();
        }

        public PartialViewResult Basket()
        {
            string count = basketService.GetOrderItemsCount().ToString();
            return PartialView("Basket", count);
        }
    }
}

AnimeStore.WebUI/Controllers/CatalogueController.cs
using System.Linq;
using System.Web.Mvc;
using AnimeStore.Domain.Abstract;
using AnimeStore.WebUI.Models;
using System;

namespace AnimeStore.WebUI.Controllers
{
    public class CatalogueController : Controller
    {
        private readonly IProductRepository productRepository;
        private const int PageSize = 4;

        public CatalogueController(IProductRepository productRepository)
        {
            this.productRepository = productRepository;
        }

        public ActionResult Index(int page = 1)
        {
            ProductsListViewModel model = new ProductsListViewModel
            {
                Products = productRepository.Products
                    .OrderBy(game => game.ProductId)
                    .Skip((page - 1) * PageSize)
                    .Take(PageSize),
                PagingInfo = new PagingInfo
                {
                    CurrentPage = page,
                    TotalPages = (int)Math.Ceiling((double)productRepository.Products.Count() / PageSize)
                }
            };
            return View(model);
        }

        public ActionResult Info(int id)
        {
            ChosenOrderItemModel model = new ChosenOrderItemModel();
            var result = productRepository.Products.FirstOrDefault(el => el.ProductId == id);
            model.Item = result;
            model.Count = 1;
            return View("Info", model);
        }

        public PartialViewResult InfoMini(int id)
        {
            ChosenOrderItemModel model = new ChosenOrderItemModel();
            var result = productRepository.Products.FirstOrDefault(el => el.ProductId == id);
            model.Item = result;
            model.Count = 1;
            return PartialView("InfoMini", model);
        }
    }
}

AnimeStore.WebUI/Views/Cart/Step1.cshtml
@using AnimeStore.WebUI.Infrastructure.Helpers
@model AnimeStore.WebUI.Models.CartIndexViewModel

@{
    ViewBag.Title = "Корзина";
}
<div class="home">
    <h2 class="special">Ваша корзина</h2>
    <table class="pricelist">
        <thead>
            <tr>
                <th></th>
                <th>Аниме</th>
                <th>Цена</th>
                <th>Кол-во</th>
                <th>Общая цена</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var line in Model.OrderItems)
            {
                <tr>
                    <td>
                        <div class="cartImage">
                            <img src="@line.Product.Image.GetProductImageUrl()" alt="image" />
                        </div>
                    </td>
                    <td>@line.Product.Name</td>
                    <td>@line.PriceForComplect.ToString("# грн")</td>
                    <td>
                        <input type="number" id="numOfComplect" class="count" value="@line.NumOfComplects" min="1" max="100" />
                    </td>
                    <td>
                        <span id="oneItemsPrice">@(line.NumOfComplects * line.PriceForComplect)</span> грн
                    </td>
                    <td id="deleteItem">
                        @Html.Hidden("orderItemId", line.OrderItemId)
                        <input class="btn" id="deteteItemButton" type="button" value="Удалить"/>
                    </td>
                </tr>
            }
        </tbody>
        <tfoot>
            <tr>
                <td colspan="4">Итого:</td>
                <td>
                    <span id="totalPrice">@Model.Order.TotalPrice.ToString()</span> грн
                </td>
                <td></td>
            </tr>
        </tfoot>
    </table>

    <div class="confirmOrder">
        <input class="btn" id="step3Button" type="button" value="Далее" />
    </div>
    <div class="boxClear"></div>
</div>

AnimeStore.WebUI/Views/Cart/Step2.cshtml
@using AnimeStore.WebUI.Models
@model LoginOrRegistrationModel

@{
    ViewBag.Title = "Регистрация";
}

<div class="home">
    <div id="orderSigtIn" class="signIN registration box">
        @using (Html.BeginForm("Step2", "Cart", FormMethod.Post))
        {
            @Html.AntiForgeryToken()
            <div id="signInValidation" class="signInValidation">@Html.ValidationMessage("modelError")</div>

            <div>
                @Html.TextBoxFor(e => e.LoginModel.Login, new
           {
               placeholder = "Логин"
           })<br />
                @Html.ValidationMessage("LoginModel.Login")
            </div>
            <div>
                @Html.PasswordFor(e => e.LoginModel.Password, new
           {
               placeholder = "Пароль"
           })<br />
                @Html.ValidationMessage("LoginModel.Password")
            </div>
            <div>
                @Html.CheckBoxFor(m => m.LoginModel.RememberMe)
                @Html.LabelFor(m => m.LoginModel.RememberMe, new { @class = "checkbox" })<br />
                @Html.ValidationMessage("LoginModel.RememberMe")
            </div>
            <input type="submit" class="btn" value="ВОЙТИ">
        }
    </div>


    @using (Html.BeginForm("Step2", "Cart", FormMethod.Post))
    {
        @Html.AntiForgeryToken()
        <div id="orderRegistration" class="signIN registration box">
            @Html.ValidationMessage("NotUniqueUserError")
            <div>
                @Html.LabelFor(m => m.RegistrationModel.Login)<br />
                @Html.TextBoxFor(m => m.RegistrationModel.Login)<br />
                @Html.ValidationMessage("RegistrationModel.Login")
            </div>
            <div>
                @Html.LabelFor(m => m.RegistrationModel.Email)<br />
                @Html.TextBoxFor(m => m.RegistrationModel.Email,
            new
            {
                type = "email"
            })<br />
                @Html.ValidationMessage("RegistrationModel.Email")
            </div>
            <div>
                @Html.LabelFor(m => m.RegistrationModel.FirstName)<br />
                @Html.TextBoxFor(m => m.RegistrationModel.FirstName)<br />
                @Html.ValidationMessage("RegistrationModel.FirstName")
            </div>
            <div>
                @Html.LabelFor(m => m.RegistrationModel.LastName)<br />
                @Html.TextBoxFor(m => m.RegistrationModel.LastName)<br />
                @Html.ValidationMessage("RegistrationModel.LastName")
            </div>
            <div>
                @Html.LabelFor(m => m.RegistrationModel.Password)<br />
                @Html.PasswordFor(m => m.RegistrationModel.Password)<br />
                @Html.ValidationMessage("RegistrationModel.Password")
            </div>
            <div>
                @Html.LabelFor(m => m.RegistrationModel.ConfirmPassword)<br />
                @Html.PasswordFor(m => m.RegistrationModel.ConfirmPassword)<br />
                @Html.ValidationMessage("RegistrationModel.ConfirmPassword")
            </div>
            <input type="submit" class="btn" value="Зарегистрироваться" />
        </div>
    }
    <div class="boxClear"></div>
</div>

AnimeStore.WebUI/Views/Cart/Step3.cshtml
@using AnimeStore.WebUI.Infrastructure.Helpers
@model AnimeStore.WebUI.Models.CartIndexViewModel

@{
    ViewBag.Title = "Подтвердите заказ";
}
<div class="home">
    <h2 class="special">Ваш заказ</h2>

    <div>
        <p><span class="special">Имя: </span>@Model.User.FirstName</p>
        <p><span class="special">Фамилия: </span>@Model.User.LastName</p>
    </div>

    <table class="pricelist">
        <thead>
            <tr>
                <th></th>
                <th>Аниме</th>
                <th>Цена</th>
                <th>Кол-во</th>
                <th>Общая цена</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var line in Model.OrderItems)
            {
                <tr>
                    <td>
                        <div class="cartImage">
                            <img src="@line.Product.Image.GetProductImageUrl()" alt="image" />
                        </div>
                    </td>
                    <td>@line.Product.Name</td>
                    <td>@line.PriceForComplect.ToString("# грн")</td>
                    <td>@line.NumOfComplects</td>
                    <td>
                        @((line.NumOfComplects * line.PriceForComplect).ToString("# грн"))
                    </td>
                </tr>
            }
        </tbody>
        <tfoot>
            <tr>
                <td colspan="4">Итого:</td>
                <td>
                    <span id="totalPrice">@Model.Order.TotalPrice.ToString()</span> грн
                </td>
            </tr>
        </tfoot>
    </table>
    <a href="@Url.Action("Step1", "Cart")">
        <div class="btn backBtn">
            Назад
        </div>
    </a>
    <div class="confirmOrder">
        <input class="btn" id="step4Button" type="button" value="Подтвердить заказ" />
    </div>
    <div class="boxClear"></div>
</div>

AnimeStore.WebUI/Views/Cart/Step4.cshtml
@{ 
    ViewBag.Title = "Заказ оформлен";
}

<div class="home">
    <p class="special">Заказ успешно оформлен. Ожидайте звонка от представителя магазина для подтверждения заказа.</p>
    <a href="@Url.Action("Index", "Catalogue")">
        <div class="btn confirmOrder">
            Вернуться в каталог
        </div>
    </a>
    <div class="boxClear"></div>
</div>