AnimeStore.WebUI/Models/Basket/AddToBasketModel.cs
namespace AnimeStore.WebUI.Models.Basket
{
    public class AddToBasketModel
    {
        public int ProductId { get; set; }
        public int Count { get; set; }
    }
}

AnimeStore.WebUI/Models/Basket/ChangeNumberOfComplectsAnswerModel.cs
namespace AnimeStore.WebUI.Models.Basket
{
    public class ChangeNumberOfComplectsAnswerModel
    {
        public int Count { get; set; }
        public decimal OneItemsPrice { get; set; }
        public decimal TotalPrice { get; set; }
    }
}

AnimeStore.WebUI/Models/Basket/ChangeNumberOfComplectsModel.cs
namespace AnimeStore.WebUI.Models.Basket
{
    public class ChangeNumberOfComplectsModel
    {
        public int OrderItemId { get; set; }
        public int OrderItemCount { get; set; }
    }
}

AnimeStore.WebUI/Models/Basket/DeleteFromBasketModel.cs
namespace AnimeStore.WebUI.Models.Basket
{
    public class DeleteFromBasketModel
    {
        public int OrderItemId { get; set; }
    }
}

AnimeStore.WebUI/Models/Basket/DeleteItemAnswerModel.cs
namespace AnimeStore.WebUI.Models.Basket
{
    public class DeleteItemAnswerModel
    {
        public int Count { get; set; }
        public decimal TotalPrice { get; set; }
    }
}

AnimeStore.WebUI/Controllers/AboutController.cs
using System.Web.Mvc;
//using WebMatrix.WebData;

namespace AnimeStore.WebUI.Controllers
{
    public class AboutController : Controller
    {
        public ActionResult Index()
        {
            //WebSecurity.RequireRoles("admin");

            return View();
        }
    }
}

AnimeStore.WebUI/Controllers/CartController.cs
using AnimeStore.Domain.Abstract;
using AnimeStore.Domain.Entities;
using AnimeStore.WebUI.Core.Abstract;
using AnimeStore.WebUI.Models;
using System.Linq;
using System.Text.RegularExpressions;
using System.Web.Mvc;

namespace AnimeStore.WebUI.Controllers
{
    public class CartController : Controller
    {
        private readonly IOrderRepository orderRepository;
        private readonly IOrderItemRepository orderItemRepository;
        private readonly IUserService userService;
        private readonly IBasketService basketService;

        public CartController(IOrderRepository orderRepository,
            IOrderItemRepository orderItemRepository, IUserService userService,
            IBasketService basketService)
        {
            this.orderRepository = orderRepository;
            this.orderItemRepository = orderItemRepository;
            this.userService = userService;
            this.basketService = basketService;
        }

        public ActionResult Step1()
        {
            Order order = basketService.GetCurrentOrder();

            if (order.OrderItems.Count == 0)
            {
                return RedirectToAction("Index", "Home");
            }

            decimal totalPrice = 0;
            foreach (var oi in order.OrderItems)
            {
                oi.PriceForComplect = oi.Product.Price;
                totalPrice += oi.PriceForComplect * oi.NumOfComplects;
                orderItemRepository.SaveOrderItem(oi);
            }
            order.TotalPrice = totalPrice;

            orderRepository.SaveOrder(order);
            CartIndexViewModel cartModel = new CartIndexViewModel();
            cartModel.Order = order;
            cartModel.OrderItems = order.OrderItems.ToList();

            return View(cartModel);
        }

        [HttpGet]
        [AllowAnonymous]
        public ActionResult Step2()
        {
            LoginOrRegistrationModel model = new LoginOrRegistrationModel();

            return View(model);
        }

        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public ActionResult Step2(LoginOrRegistrationModel model)
        {

            if (model.LoginModel != null)
            {
                if (ModelState.IsValid && userService.LoginUser(model.LoginModel.Login, 
                    model.LoginModel.Password, model.LoginModel.RememberMe))
                {
                    return RedirectToAction("Step3");
                }

                ModelState.AddModelError("modelError",
                            "Неверный логин или пароль");
            }
            else
            {
                if (!ModelState.IsValid)
                {
                    return View(model);
                } 

                if (userService.IsUserWithLoginExists(model.RegistrationModel.Login))
                {
                    ModelState.AddModelError("NotUniqueUserError",
                        "Пользователь с таким логином уже зарегистрирован!");
                }
                Regex regex = new Regex("^[a-zA-Z0-9]*$");
                if (!regex.IsMatch(model.RegistrationModel.Login))
                {
                    ModelState.AddModelError("RegistrationModel.Login",
                        "Логин должен состоять только с цифр и латинских букв");
                }
                if (userService.IsUserWithEmailExists(model.RegistrationModel.Email))
                {
                    ModelState.AddModelError("NotUniqueUserError",
                        "Пользователь с таким email уже зарегистрирован!");
                }
                regex = new Regex("[0-9]+");
                if (regex.IsMatch(model.RegistrationModel.FirstName))
                {
                    ModelState.AddModelError("RegistrationModel.FirstName",
                        "В имени не должно быть цифр");
                }
                if (regex.IsMatch(model.RegistrationModel.LastName))
                {
                    ModelState.AddModelError("RegistrationModel.LastName",
                        "В фамилии не должно быть цифр");
                }
                if (ModelState.IsValid)
                {
                    CreateUserModel createUserModel = userService.CreateUser(model.RegistrationModel);
                    if (createUserModel.IsSuccess)
                    {
                        userService.LoginUser(model.RegistrationModel.Login, model.RegistrationModel.Password);
                        return RedirectToAction("Step3");
                    }

                    ModelState.AddModelError("NotUniqueUserError", createUserModel.ErrorMessage);
                }
            }

            return View(model);
        }

        public ActionResult Step3()
        {
            if (!userService.IsAuthenticated())
            {
                return RedirectToAction("Step2");
            }

            Order order = basketService.GetCurrentOrder();

            if (order.OrderItems.Count == 0)
            {
                return RedirectToAction("Index", "Home");
            }

            CartIndexViewModel cartModel = new CartIndexViewModel();
            cartModel.Order = order;
            cartModel.OrderItems = order.OrderItems.ToList();
            cartModel.User = userService.GetCurrentUser();

            return View(cartModel);
        }

        public ActionResult Step4()
        {
            if (!userService.IsAuthenticated())
            {
                return RedirectToAction("Step2");
            }

            Order order = basketService.GetCurrentOrder();

            if (order.OrderItems.Count == 0)
            {
                return RedirectToAction("Index", "Home");
            }

            basketService.ConfirmOrder();

            return View();
        }

        public PartialViewResult Basket()
        {
            string count = basketService.GetOrderItemsCount().ToString();
            return PartialView("Basket", count);
        }
    }
}

AnimeStore.WebUI/Controllers/NewsController.cs
using AnimeStore.Domain.Abstract;
using AnimeStore.Domain.Entities;
using AnimeStore.WebUI.Areas.Admin.Models;
using AnimeStore.WebUI.Models;
using System;
using System.Linq;
using System.Web.Mvc;

namespace AnimeStore.WebUI.Controllers
{
    public class NewsController : Controller
    {
        private readonly INewsRepository newsRepository;
        public const int PageSize = 3;

        public NewsController(INewsRepository newsRepository)
        {
            this.newsRepository = newsRepository;
        }

        public ActionResult Index(int page = 1)
        {
            NewsListViewModel model = new NewsListViewModel
            {
                News = newsRepository.News
                                   .OrderByDescending(news => news.NewsId)
                                   .Skip((page - 1) * PageSize)
                                   .Take(PageSize),
                PagingInfo = new PagingInfo
                {
                    CurrentPage = page,
                    TotalPages = (int)Math.Ceiling((double)newsRepository.News.Count() / PageSize)
                }
            };
            return View(model);
        }

        public ActionResult Info(int id)
        {
            string returnUrl = System.Web.HttpContext.Current.Request.UrlReferrer != null ? System.Web.HttpContext.Current.Request.UrlReferrer.ToString() : Url.Action("Index");

            News news = newsRepository.News.First(n => n.NewsId == id);
            if (news == null)
            {
                return Redirect(returnUrl);
            }

            EditNewsViewModel model = new EditNewsViewModel();
            model.News = news;
            model.ReturnUrl = returnUrl;

            return View(model);
        }
    }
}

AnimeStore.WebUI/Controllers/SearchController.cs
using AnimeStore.WebUI.Core.Abstract;
using AnimeStore.WebUI.Models;
using System;
using System.Linq;
using System.Web.Mvc;

namespace AnimeStore.WebUI.Controllers
{
    public class SearchController : Controller
    {
        private readonly ISearchService searchService;
        public const int PageSize = 3;

        public SearchController(ISearchService searchService)
        {
            this.searchService = searchService;
        }

        public ActionResult Index()
        {
            return View();
        }

        public PartialViewResult SearchRow()
        {
            return PartialView("SearchRow");
        }

        public ActionResult Search(string q, int page = 1)
        {
            var results = searchService.GetSearchResult(q);
            SearchResultsViewModel model = new SearchResultsViewModel
            {
                SearchResults = results
                                   .Skip((page - 1) * PageSize)
                                   .Take(PageSize).ToList(),
                PagingInfo = new PagingInfo
                {
                    CurrentPage = page,
                    TotalPages = (int)Math.Ceiling((double)results.Count / PageSize)
                },
                SearchKeyWord = q
            };

            return View("SearchResult", model);
        }
    }
}

AnimeStore.WebUI/Views/Shared/Basket.cshtml
@model string

<p>В корзине <span id="basketItemsCount">@Model</span> аниме</p>
<a href="@Url.Action("Step1", "Cart")">
    <div class="btn">
        Корзина
    </div>
</a>

AnimeStore.WebUI/Views/Shared/Info.cshtml
@using AnimeStore.WebUI.Infrastructure.Helpers
@using AnimeStore.WebUI.Models
@model ChosenOrderItemModel

@{
    ViewBag.Title = Model.Item.Name;
}

<div class="catalogue">
    <div class="animeP">
        <p class="special">
            @Model.Item.Name
        </p>
        <div id="productInfoBlock" class="productInfoBlock">
            @if (Model.Item.StockAvailability)
            {
                <input id="productId" type="hidden" value="@Model.Item.ProductId" />
                <p>
                    <input type="number" id="numOfComplect" class="count" value="1" min="1" max="10" />
                    <input type="button" id="addToCart" class="btn" value="Добавить в корзину" />
                </p>
            }
            else
            {
                <p>
                    <span class="description">Нет в наличии</span>
                </p>
            }
        </div>
        <div>
            <p>
                <span class="description">Цена:</span> @Model.Item.Price.ToString("# грн")
            </p>
            <p>
                <span class="description">Количество дисков в комплекте:</span> @Model.Item.NumOfDiscsInComplect.ToString("# шт.")
            </p>
            <p>
            <p>
                <span class="description">Год: </span>@Model.Item.Year
            </p>
            <p>
                <span class="description">Тип: </span>
                @if (Model.Item.Types.Count == 0)
                {
                    @:-
                }
                else
                {
                    for (int i = 0; i < Model.Item.Types.Count - 1; i++)
                    {
                        @Model.Item.Types.ElementAt(i).Name@:,
                    }
                    @Model.Item.Types.ElementAt(Model.Item.Types.Count - 1).Name
                }
            </p>
            <p>
                <span class="description">Жанр: </span>
                @if (Model.Item.Genres.Count == 0)
                {
                    @:-
                }
                else
                {
                    for (int i = 0; i < Model.Item.Genres.Count - 1; i++)
                    {
                        @Model.Item.Genres.ElementAt(i).Name@:,
                    }
                    @Model.Item.Genres.ElementAt(Model.Item.Genres.Count - 1).Name
                }
            </p>
            <p>
                <span class="description">Количество эпизодов: </span>@Model.Item.NumOfSeries
            </p>
            <p>
                <span class="description">Режиссёр: </span>@Model.Item.Director<br />
                <span class="description">Автор оригинала: </span>@Model.Item.Scriptwriter
            </p>
            <p>
                <span class="description">Описание:</span><br />
                @Model.Item.Description
            </p>
            <p class="categoryAll">
                (@Model.Item.Category) - категория
            </p>
        </div>
        <div class="image">
            <img src="@Model.Item.Image.GetProductImageUrl()" alt="@Model.Item.Name" />
        </div>
    </div>
</div>

AnimeStore.WebUI/Views/Shared/InfoMini.cshtml
@using AnimeStore.WebUI.Infrastructure.Helpers
@using AnimeStore.WebUI.Models
@model ChosenOrderItemModel
<div class="catalogue">
    <div class="anime">
        <p class="special">
            @Model.Item.Name
        </p>
        <div class="InLine">
            <input type="button" class="btn moreInfoProduct" value="Подробнее" onclick="GetProductInfo('@Model.Item.ProductId')" />
            <div id="productInfoBlock">
                @if (@Model.Item.StockAvailability)
                {
                    <input id="productId" type="hidden" value="@Model.Item.ProductId" />
                    <input type="button" id="addToCart" class="btn" value="Добавить в корзину" />
                    <p><input type="number" id="numOfComplect" class="count" value="1" min="1" max="10" /></p>
                }
                else
                {
                    <p>
                        <span class="description">Нет в наличии</span>
                    </p>
                }
            </div>
        </div>
        <div>
            <p>
                <span class="description">Цена:</span> @Model.Item.Price.ToString("# грн")
            </p>
            <p class="categoryAll">
                (@Model.Item.Category) - категория
            </p>
        </div>
        <div class="image">
            <img src="@Model.Item.Image.GetProductImageUrl()" alt="@Model.Item.Name" />
        </div>
    </div>
</div>

AnimeStore.WebUI/Views/Shared/SearchRow.cshtml
<div id="searchDiv" class="searchDiv">
    <input type="search" id="searchString" class="searchString" placeholder="поиск"/>
    <input type="button" id="searchButton" class="searchButton" value="Найти"/>
</div>

AnimeStore.WebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link rel="shortcut icon" type="image/ico" href="~/Content/image/favicon.ico?v=2">
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/jquery")
    <title>@ViewBag.Title</title>
</head>
<body onload="digitalWatch()">
    <div id="digital_watch" class="digitalWatch">
        <p>
        </p>
    </div>
    <div>
        <ul class="menu">
            <li>@Html.ActionLink("Главная", "Index", "Home")</li>
            <li>@Html.ActionLink("Новости", "Index", "News")</li>
            <li>@Html.ActionLink("Каталог", "Index", "Catalogue")</li>
            @if (WebSecurity.IsAuthenticated)
            {
                <li>@Html.ActionLink("Личный кабинет", "Index", "Cabinet")</li>
            }
            <li>
                @Html.ActionLink("О магазине", "Index", "About", null,
                new
                {
                    onmouseover = "About()",
                    onmouseout = "AboutHover()"
                })
            </li>
        </ul>
        <div class="aboutSite">
            <p>
                Автор сайта - DarkKnight<br />
                Бойко Алла
            </p>
        </div>
    </div>
    <div class="registrationA special">
        @if (WebSecurity.IsAuthenticated)
        {
            @WebSecurity.CurrentUserName<br />
            @Html.ActionLink("Выйти", "SignOut", "Authentication")
        }
        else
        {
            @Html.ActionLink("Войти", "SignIn", "Authentication")<br />
            @Html.ActionLink("Регистрация", "Registration", "Authentication")
        }
        <div class="special">_________</div>
        @Html.Action("Basket", "Cart")
        <div class="special">_________</div>
        <p>@Html.Action("SearchRow", "Search")</p>
    </div>
    <div>
        @RenderBody()
    </div>
    @Scripts.Render("~/bundles/myscripts")
    @RenderSection("scripts", required: false)
</body>
</html>
<footer>
    <div class="footer">
        Copyright © Alla Boiko, @System.DateTime.Now.Year
    </div>
</footer>